name: Music-box-a CI
 
on:
  push:
    branches: [ dev ]
   
  pull_request:
    branches: [ dev ]
 
jobs:
  testIncomingPush:
 
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: sets environmental variables
          env:
            MONGODB_URI: ${{music-box-a.MONGODB_URI}}
            GENRE_LINK: ${{music-box-a.GENRE_LINK}}
            ARTIST_LINK: ${{music-box-a.ARTIST_LINK}}
            SECRET_TEXT: ${{music-box-a.SECRET_TEXT}}
            BCRYPT_SALT: ${{music-box-a.BCRYPT_SALT}}
            CLIENT_URL: ${{music-box-a.CLIENT_URL}}
            JWT_SECRET_KEY: ${{music-box-a.JWT_SECRET_KEY}}
            GOOGLE_CLIENT_ID : ${{music-box-a.GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET : ${{music-box-a.GOOGLE_CLIENT_SECRET }}
            FACEBOOK_CLIENT_ID : ${{music-box-a.FACEBOOK_CLIENT_ID }}
            FACEBOOK_CLIENT_SECRET : ${{music-box-a.FACEBOOK_CLIENT_SECRET }}
      - run: yarn
      - run: yarn test

